/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeficitRouteImport } from './routes/deficit'
import { Route as MapRouteImport } from './routes/map'
import { Route as TrendsRouteImport } from './routes/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeficitRoute = DeficitRouteImport.update({
  id: '/deficit',
  path: '/deficit',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deficit': typeof DeficitRoute
  '/map': typeof MapRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deficit': typeof DeficitRoute
  '/map': typeof MapRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deficit': typeof DeficitRoute
  '/map': typeof MapRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deficit' | '/map' | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deficit' | '/map' | '/trends'
  id: '__root__' | '/' | '/deficit' | '/map' | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeficitRoute: typeof DeficitRoute
  MapRoute: typeof MapRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deficit': {
      id: '/deficit'
      path: '/deficit'
      fullPath: '/deficit'
      preLoaderRoute: typeof DeficitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeficitRoute: DeficitRoute,
  MapRoute: MapRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
